# PID gains for the steer_bot_hardware_gazebo plugin.
gazebo_ros_control:    
    pid_gains:
        front_wheel_joint:
            p: 100000.0
            d: 10.0
            i: 0.50
            i_clamp: 3.0
        base_link2front_link:
            p: 100000.0
            d: 10.0
            i: 0.50
            i_clamp: 3.0

